//********************************************************************************
// Automatically generated by CppStubGenerator
//********************************************************************************

#ifndef TEST1_STUB_H
#define TEST1_STUB_H

#include "Test1.h"
#include <string.h>

namespace Test1_Stub
{
    namespace Func1
    {
        extern bool called;
        extern int callCount;
    }
    namespace Func2
    {
        extern bool called;
        extern int callCount;
        extern int val;
    }
    namespace Func2
    {
        extern bool called;
        extern int callCount;
        extern bool retVal;
        extern char* str;
        extern int strSize;
    }
    namespace Func3
    {
        extern bool called;
        extern int callCount;
        extern int retVal;
        extern int outParam;
    }
    namespace Method1
    {
        extern bool called;
        extern int callCount;
    }
    namespace Method2
    {
        extern bool called;
        extern int callCount;
        extern bool retVal;
        extern char* inPtr;
        extern int inPtrSize;
        extern char* outPtr;
        extern int outPtrSize;
        extern int inRef;
        extern short outRef;
    }
}

#define INITIALIZE_TEST1_STUB() \
    Test1_Stub::Func1::called = false; \
    Test1_Stub::Func1::callCount = 0; \
    Test1_Stub::Func2::called = false; \
    Test1_Stub::Func2::callCount = 0; \
    Test1_Stub::Func2::val = int(0); \
    Test1_Stub::Func2::called = false; \
    Test1_Stub::Func2::callCount = 0; \
    Test1_Stub::Func2::retVal = false; \
    Test1_Stub::Func2::str = (char*)(0); \
    Test1_Stub::Func2::strSize = int(0); \
    Test1_Stub::Func3::called = false; \
    Test1_Stub::Func3::callCount = 0; \
    Test1_Stub::Func3::retVal = int(0); \
    Test1_Stub::Func3::outParam = int(0); \
    Test1_Stub::Method1::called = false; \
    Test1_Stub::Method1::callCount = 0; \
    Test1_Stub::Method2::called = false; \
    Test1_Stub::Method2::callCount = 0; \
    Test1_Stub::Method2::retVal = false; \
    Test1_Stub::Method2::inPtr = (char*)(0); \
    Test1_Stub::Method2::inPtrSize = int(0); \
    Test1_Stub::Method2::outPtr = (char*)(0); \
    Test1_Stub::Method2::outPtrSize = int(0); \
    Test1_Stub::Method2::inRef = int(0); \
    Test1_Stub::Method2::outRef = short(0); \

#endif//TEST1_STUB_H

